// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs0SaqJ5KKcKoUwuTtIK9wLEAq9Ud-29s',
    appId: '1:926699941208:android:c20ec8401f1769f25ac92d',
    messagingSenderId: '926699941208',
    projectId: 'fir-test-8b5bf',
    storageBucket: 'fir-test-8b5bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoj3efuiZXn18bvwtybThIp6O0CMVCDFY',
    appId: '1:926699941208:ios:23ba63818bccdec65ac92d',
    messagingSenderId: '926699941208',
    projectId: 'fir-test-8b5bf',
    storageBucket: 'fir-test-8b5bf.appspot.com',
    iosClientId: '926699941208-6bthppe1mnntj6a224un4mic5dici15b.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceFirebase',
  );
}
